language: Swift
osx_image: xcode10.2.1
xcode_workspace: TravisDemo.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
- brew update
- rvm use system
- sudo gem install cocoapods
- pod setup
- pod install
- pod env
script:
- set -o pipefail
- xcodebuild -workspace TravisDemo.xcworkspace -scheme TravisDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#- xcodebuild -showsdks xcodebuild clean && xcodebuild build 
#script: 
  #- xcodebuild -project TMSC.xcodeproj -target TMSC_Dev -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  #- xcodebuild -workspace TMSC.xcworkspace -scheme TMSC_Dev -sdk iphoneos clean build
  #- xcodebuild -showsdks xcodebuild clean && xcodebuild build -scheme TMSC_Dev ONLY_ACTIVE_ARCH=NO
