language: Swift
osx_image: xcode10.2.1
xcode_workspace: TravisDemo.xcworkspace
xcode_scheme: TravisDemo
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

script: 
#- set -o pipefail
#- xcodebuild clean build -workspace TravisDemo/TravisDemo.xcworkspace -scheme TravisDemo -sdk iphonesimulator -configuration Debug 
- xcodebuild -workspace TravisDemo.xcworkspace -scheme TravisDemo -sdk iphonesimulator