language: Swift
osx_image: xcode10.2.1
xcode_workspace: TravisDemo.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
    - brew update
    - brew install xctool
  